"""add report_md to messages

Revision ID: f750d046b573
Revises: 5feb99a753b2
Create Date: 2026-02-03 11:04:38.456478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f750d046b573'
down_revision: Union[str, Sequence[str], None] = '5feb99a753b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('report_md', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'report_md')
    # ### end Alembic commands ###
